export const BASE_URL = 'https://test.v5.pryaniky.com'
export const SIGN_IN = '/ru/data/v3/testmethods/docs/login'
export const GET_ALL_DOCS = '/ru/data/v3/testmethods/docs/userdocs/get'
export const UPDATE_USER_DOC_BY_ID = '/ru/data/v3/testmethods/docs/userdocs/set/'
export const DELETE_USER_DOC_BY_ID = '/ru/data/v3/testmethods/docs/userdocs/delete/'
export const CREATE_NEW_USER_DOC = '/ru/data/v3/testmethods/docs/userdocs/create'